### ISSUE TITLE
Hidden postage and memo in the label call

### ISSUE THREAD

**Issue by dreamzoner** [jzempel/stamps#9]
Hello Jonathan,

I am trying to figure out how to get these work and hopefully you can shed some light on these.

- Hidden Postage
I appended the addon but the postage still appeared on the label
....
addOn = service.create_add_on()                                              
addOn.AddOnType = 'SC-A-HP'                                                  
ret_val.AddOns.AddOnV7.append(addOn) 
....

- memo:
I added memo in the call to see if it would work, but it didn't appear on the label

def get_label(self, from_address, to_address, rate, transaction_id, sample=False):
      return self.call("CreateIndicium", IntegratorTxID=transaction_id,
                Rate=rate, From=from_address, To=to_address, SampleOnly=sample, memo='test order')

**Comment by jzempel** [comment]
Hi @dreamzoner, both of your code samples look valid but neither are features I've tried with the Stamps.com API. I've reached out to Stamps for support on this kind of stuff and usually learn that there is some incompatibility (can't combine certain add-on types) or the feature is not supported in test mode (which kind of defeats the purpose of having a test).

Anyway, I think your best bet is to reach out to sws-support@stamps.com on this one. Good luck. Please consider commenting back if they provide a working solution.

**Comment by dreamzoner** [comment]
Hi @jzempel, thanks for your prompt response; I was able to get memo and hidden postage on the label.

I checked with Stamps and the issue was I used the IntegratorTxID; CreateIndicium is idempotent, the call can be made multiple times to get the same response back when using the same IntegratorTxID. Reusing an IntegratorTxID will recall the original request that used it.

**Comment by jzempel** [comment]
@dreamzoner I've totally been bitten by the same issue while testing. Glad you were able to get it sorted.
